# Form implementation generated from reading ui file 'view/MainVentana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 598)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/CarMec.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/CarMec.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background:rgb(85, 85, 85);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SideBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.SideBar.setMinimumSize(QtCore.QSize(200, 0))
        self.SideBar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.SideBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SideBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SideBar.setObjectName("SideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SideBar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Logo = QtWidgets.QFrame(parent=self.SideBar)
        self.Logo.setStyleSheet("QLabel{\n"
"color:rgb(245, 245, 245);\n"
"font:77 10pt \'Arial Black\';\n"
"}\n"
"QPushButton{\n"
"border-radius: 12px;\n"
"color:rgb(238, 238, 238);\n"
"background-color:rgb(186, 186, 186);\n"
"padding: 7px 7px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #04AA6D; /* Green */\n"
"color: white;\n"
"}")
        self.Logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Logo)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMenu = QtWidgets.QPushButton(parent=self.Logo)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/CarMec.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMenu.setIcon(icon1)
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout.addWidget(self.btnMenu)
        self.label = QtWidgets.QLabel(parent=self.Logo)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout.addWidget(self.Logo)
        self.frame_2 = QtWidgets.QFrame(parent=self.SideBar)
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgb(140, 140, 140);\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(166, 200, 185); \n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color: rgb(47, 39, 39);\n"
"text-align: center;\n"
"font:77 16px \'ArialBlack\';\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(133, 166, 153); \n"
"border-top-left-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"color: rgb(238, 238, 238);\n"
"text-align: center;\n"
"font:77 16px \'ArialBlack\';\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnServicios = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnServicios.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("view/../../../../../Downloads/icons8-servicio-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnServicios.setIcon(icon2)
        self.btnServicios.setObjectName("btnServicios")
        self.verticalLayout_3.addWidget(self.btnServicios)
        self.btnClientes = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnClientes.setMinimumSize(QtCore.QSize(0, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/icons8-clientes-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnClientes.setIcon(icon3)
        self.btnClientes.setObjectName("btnClientes")
        self.verticalLayout_3.addWidget(self.btnClientes)
        self.btnUsuarios = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnUsuarios.setMinimumSize(QtCore.QSize(0, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/icons8-usuario-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnUsuarios.setIcon(icon4)
        self.btnUsuarios.setObjectName("btnUsuarios")
        self.verticalLayout_3.addWidget(self.btnUsuarios)
        self.btnConfig = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnConfig.setMinimumSize(QtCore.QSize(0, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/icons8-config-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnConfig.setIcon(icon5)
        self.btnConfig.setObjectName("btnConfig")
        self.verticalLayout_3.addWidget(self.btnConfig)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout_2.addWidget(self.SideBar)
        self.Contenido = QtWidgets.QFrame(parent=self.centralwidget)
        self.Contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Contenido.setObjectName("Contenido")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Contenido)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Contenido)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_servicios = QtWidgets.QWidget()
        self.page_servicios.setObjectName("page_servicios")
        self.stackedWidget.addWidget(self.page_servicios)
        self.page_usuarios = QtWidgets.QWidget()
        self.page_usuarios.setObjectName("page_usuarios")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_usuarios)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(parent=self.page_usuarios)
        self.frame_5.setStyleSheet("QLabel{\n"
"color:rgb(245, 245, 245);\n"
"font:77 15pt \'Arial Black\';\n"
"font-weight: bold;\n"
"}\n"
"QPushButton{\n"
"border-radius: 12px;\n"
"color:rgb(238, 238, 238);\n"
"background-color:rgb(186, 186, 186);\n"
"padding: 7px 7px;\n"
"  text-align: center;\n"
"  font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #04AA6D; /* Green */\n"
"color: white;\n"
"}\n"
"QLineEdit{\n"
"padding: 12px 20px;\n"
"margin: 8px 0;\n"
"border: 2px solid #fff;\n"
"border-radius: 5px;\n"
"font:77 12px \'Arial Black\';\n"
"color:rgb(238, 238, 238);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(2, 1, 2, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineSearchUser = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineSearchUser.setObjectName("lineSearchUser")
        self.horizontalLayout_5.addWidget(self.lineSearchUser)
        self.btnBuscarUser = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnBuscarUser.setText("")
        self.btnBuscarUser.setIconSize(QtCore.QSize(30, 30))
        self.btnBuscarUser.setObjectName("btnBuscarUser")
        self.horizontalLayout_5.addWidget(self.btnBuscarUser)
        self.btnNuevoUser = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnNuevoUser.setStyleSheet("QPushButton{\n"
"    background:rgb(29, 159, 48);\n"
"}")
        self.btnNuevoUser.setIconSize(QtCore.QSize(30, 30))
        self.btnNuevoUser.setObjectName("btnNuevoUser")
        self.horizontalLayout_5.addWidget(self.btnNuevoUser)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.page_usuarios)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_6)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"        color: rgb(164, 255, 225);        \n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"}\n"
" QTabBar::tab:selected {\n"
"        color: white;        \n"
"        font-weight: bold;   \n"
"        background:rgb(94, 94, 255);\n"
"        border-color:rgb(255, 255, 255);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 8)
        self.stackedWidget.addWidget(self.page_usuarios)
        self.page_config = QtWidgets.QWidget()
        self.page_config.setObjectName("page_config")
        self.stackedWidget.addWidget(self.page_config)
        self.page_clientes = QtWidgets.QWidget()
        self.page_clientes.setObjectName("page_clientes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_clientes)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.page_clientes)
        self.frame.setStyleSheet("QLabel{\n"
"color:rgb(245, 245, 245);\n"
"font:77 10pt \'Arial Black\';\n"
"}\n"
"QPushButton{\n"
"border-radius: 12px;\n"
"color:rgb(238, 238, 238);\n"
"background-color:rgb(186, 186, 186);\n"
"padding: 7px 7px;\n"
"  text-align: center;\n"
"  font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #04AA6D; /* Green */\n"
"color: white;\n"
"}\n"
"QLineEdit{\n"
"padding: 12px 20px;\n"
"margin: 8px 0;\n"
"border: 2px solid #fff;\n"
"border-radius: 5px;\n"
"font:77 12px \'Arial Black\';\n"
"color:rgb(238, 238, 238);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.textSeach = QtWidgets.QLineEdit(parent=self.frame)
        self.textSeach.setObjectName("textSeach")
        self.horizontalLayout_3.addWidget(self.textSeach)
        self.bSearchClient = QtWidgets.QPushButton(parent=self.frame)
        self.bSearchClient.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/search_magnifyng_glass_find_locate_icon_123485.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bSearchClient.setIcon(icon6)
        self.bSearchClient.setIconSize(QtCore.QSize(30, 30))
        self.bSearchClient.setObjectName("bSearchClient")
        self.horizontalLayout_3.addWidget(self.bSearchClient)
        self.expoCliPdf = QtWidgets.QPushButton(parent=self.frame)
        self.expoCliPdf.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/pdf_filetype_icon_177525.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.expoCliPdf.setIcon(icon7)
        self.expoCliPdf.setIconSize(QtCore.QSize(30, 30))
        self.expoCliPdf.setObjectName("expoCliPdf")
        self.horizontalLayout_3.addWidget(self.expoCliPdf)
        self.exExcCli = QtWidgets.QPushButton(parent=self.frame)
        self.exExcCli.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/file_type_excel_icon_130611.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exExcCli.setIcon(icon8)
        self.exExcCli.setIconSize(QtCore.QSize(30, 30))
        self.exExcCli.setObjectName("exExcCli")
        self.horizontalLayout_3.addWidget(self.exExcCli)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=self.page_clientes)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setStyleSheet("QLabel{\n"
"color:rgb(245, 245, 245);\n"
"font:77 10pt \'Arial Black\';\n"
"}\n"
"QPushButton{\n"
"border-radius: 12px;\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color:rgb(186, 186, 186);\n"
"padding: 7px 7px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"font-weight: bold;\n"
"background-color: #04AA6D; /* Green */\n"
"color: white;\n"
"}\n"
"QLineEdit{\n"
"padding: 12px 20px;\n"
"margin: 8px 0;\n"
"box-sizing: border-box;\n"
"border: 2px solid #fff;\n"
"border-radius: 5px;\n"
"font:77 12px \'Arial Black\';\n"
"color:rgb(238, 238, 238);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnAddClient = QtWidgets.QPushButton(parent=self.frame_4)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/Add_User-80_icon-icons.com_57380.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAddClient.setIcon(icon9)
        self.btnAddClient.setIconSize(QtCore.QSize(20, 20))
        self.btnAddClient.setObjectName("btnAddClient")
        self.horizontalLayout_4.addWidget(self.btnAddClient)
        self.btnLoadClient = QtWidgets.QPushButton(parent=self.frame_4)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("view/../../../../../../../Downloads/reload_78477.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLoadClient.setIcon(icon10)
        self.btnLoadClient.setIconSize(QtCore.QSize(20, 20))
        self.btnLoadClient.setObjectName("btnLoadClient")
        self.horizontalLayout_4.addWidget(self.btnLoadClient)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.listaClientes = QtWidgets.QTableWidget(parent=self.frame_3)
        self.listaClientes.setObjectName("listaClientes")
        self.listaClientes.setColumnCount(0)
        self.listaClientes.setRowCount(0)
        self.verticalLayout_5.addWidget(self.listaClientes)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 8)
        self.stackedWidget.addWidget(self.page_clientes)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Candia Card"))
        self.btnMenu.setText(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "CANDIA CAR"))
        self.btnServicios.setText(_translate("MainWindow", "SERVICIOS"))
        self.btnClientes.setText(_translate("MainWindow", "CLIENTES"))
        self.btnUsuarios.setText(_translate("MainWindow", "USUARIOS"))
        self.btnConfig.setText(_translate("MainWindow", "CONFIG..."))
        self.label_3.setText(_translate("MainWindow", "BUSCAR USUARIO"))
        self.btnNuevoUser.setText(_translate("MainWindow", "Nuevo"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Usuarios"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Permiso"))
        self.label_2.setText(_translate("MainWindow", "BUSCAR CLIENTE"))
        self.btnAddClient.setText(_translate("MainWindow", "Nuevo Cliente"))
        self.btnLoadClient.setText(_translate("MainWindow", "Refrescar"))
